// Map ID -> image. Metro bundler exige des chemins litteraux dans require().
const IMAGES = {
  1:  require('../../assets/sanctuary-references/sanctuaire-01/sanctuaire_01.jpeg'),
  2:  require('../../assets/sanctuary-references/sanctuaire-02/sanctuaire_02.jpeg'),
  3:  require('../../assets/sanctuary-references/sanctuaire-03/sanctuaire_03.jpeg'),
  4:  require('../../assets/sanctuary-references/sanctuaire-04/sanctuaire_04.jpeg'),
  5:  require('../../assets/sanctuary-references/sanctuaire-05/sanctuaire_05.jpeg'),
  6:  require('../../assets/sanctuary-references/sanctuaire-06/sanctuaire_06.jpeg'),
  7:  require('../../assets/sanctuary-references/sanctuaire-07/sanctuaire_07.jpeg'),
  8:  require('../../assets/sanctuary-references/sanctuaire-08/sanctuaire_08.jpeg'),
  9:  require('../../assets/sanctuary-references/sanctuaire-09/sanctuaire_09.jpeg'),
  10: require('../../assets/sanctuary-references/sanctuaire-10/sanctuaire_10.jpeg'),
  11: require('../../assets/sanctuary-references/sanctuaire-11/sanctuaire_11.jpeg'),
  12: require('../../assets/sanctuary-references/sanctuaire-12/sanctuaire_12.jpeg'),
  13: require('../../assets/sanctuary-references/sanctuaire-13/sanctuaire_13.jpeg'),
  14: require('../../assets/sanctuary-references/sanctuaire-14/sanctuaire_14.jpeg'),
  15: require('../../assets/sanctuary-references/sanctuaire-15/sanctuaire_15.jpeg'),
  16: require('../../assets/sanctuary-references/sanctuaire-16/sanctuaire_16.jpeg'),
  17: require('../../assets/sanctuary-references/sanctuaire-17/sanctuaire_17.jpeg'),
  18: require('../../assets/sanctuary-references/sanctuaire-18/sanctuaire_18.jpeg'),
  19: require('../../assets/sanctuary-references/sanctuaire-19/sanctuaire_19.jpeg'),
  20: require('../../assets/sanctuary-references/sanctuaire-20/sanctuaire_20.jpeg'),
  21: require('../../assets/sanctuary-references/sanctuaire-21/sanctuaire_21.jpeg'),
  22: require('../../assets/sanctuary-references/sanctuaire-22/sanctuaire_22.jpeg'),
  23: require('../../assets/sanctuary-references/sanctuaire-23/sanctuaire_23.jpeg'),
  24: require('../../assets/sanctuary-references/sanctuaire-24/sanctuaire_24.jpeg'),
  25: require('../../assets/sanctuary-references/sanctuaire-25/sanctuaire_25.jpeg'),
  26: require('../../assets/sanctuary-references/sanctuaire-26/sanctuaire_26.jpeg'),
  27: require('../../assets/sanctuary-references/sanctuaire-27/sanctuaire_27.jpeg'),
  28: require('../../assets/sanctuary-references/sanctuaire-28/sanctuaire_28.jpeg'),
  29: require('../../assets/sanctuary-references/sanctuaire-29/sanctuaire_29.jpeg'),
  30: require('../../assets/sanctuary-references/sanctuaire-30/sanctuaire_30.jpeg'),
  31: require('../../assets/sanctuary-references/sanctuaire-31/sanctuaire_31.jpeg'),
  32: require('../../assets/sanctuary-references/sanctuaire-32/sanctuaire_32.jpeg'),
  33: require('../../assets/sanctuary-references/sanctuaire-33/sanctuaire_33.jpeg'),
  34: require('../../assets/sanctuary-references/sanctuaire-34/sanctuaire_34.jpeg'),
  35: require('../../assets/sanctuary-references/sanctuaire-35/sanctuaire_35.jpeg'),
  36: require('../../assets/sanctuary-references/sanctuaire-36/sanctuaire_36.jpeg'),
  37: require('../../assets/sanctuary-references/sanctuaire-37/sanctuaire_37.jpeg'),
  38: require('../../assets/sanctuary-references/sanctuaire-38/sanctuaire_38.jpeg'),
  39: require('../../assets/sanctuary-references/sanctuaire-39/sanctuaire_39.jpeg'),
  40: require('../../assets/sanctuary-references/sanctuaire-40/sanctuaire_40.jpeg'),
  41: require('../../assets/sanctuary-references/sanctuaire-41/sanctuaire_41.jpeg'),
  42: require('../../assets/sanctuary-references/sanctuaire-42/sanctuaire_42.jpeg'),
  43: require('../../assets/sanctuary-references/sanctuaire-43/sanctuaire_43.jpeg'),
  44: require('../../assets/sanctuary-references/sanctuaire-44/sanctuaire_44.jpeg'),
  45: require('../../assets/sanctuary-references/sanctuaire-45/sanctuaire_45.jpeg'),
  46: require('../../assets/sanctuary-references/sanctuaire-46/sanctuaire_46.jpeg'),
  47: require('../../assets/sanctuary-references/sanctuaire-47/sanctuaire_47.jpeg'),
  48: require('../../assets/sanctuary-references/sanctuaire-48/sanctuaire_48.jpeg'),
  49: require('../../assets/sanctuary-references/sanctuaire-49/sanctuaire_49.jpeg'),
  50: require('../../assets/sanctuary-references/sanctuaire-50/sanctuaire_50.jpeg'),
  51: require('../../assets/sanctuary-references/sanctuaire-51/sanctuaire_51.jpeg'),
  52: require('../../assets/sanctuary-references/sanctuaire-52/sanctuaire_52.jpeg'),
  53: require('../../assets/sanctuary-references/sanctuaire-53/sanctuaire_53.jpeg'),
};

export function getSanctuaryImage(id) {
  return IMAGES[id] ?? null;
}

export const SANCTUARY_COUNT = 53;
